In [29]:
import numpy as np
import sympy as sp

In [30]:
# Ex1
def isLinearCombanation(A, w):
  A_extended = np.column_stack((A,w))
  rank_A = np.linalg.matrix_rank(A)
  rank_A_extend = np.linalg.matrix_rank(A_extended)
  return rank_A == rank_A_extend

def check_linear_combination(*vectors, w, character):
  A = np.array(vectors).T
  w = np.array(w)
  print("%s: %s" %(character,str(isLinearCombanation(A, w))))

# test case
# a
v1,v2,v3= [1,2,3,4],[-1,0,1,3],[0,5,-6,8]
w = [3,-6,17,11]
check_linear_combination(v1,v2,v3, w=w, character='a')

# b
v1,v2,v3= [1,1,2,2],[2,3,5,6],[2,-1,3,6]
w = [0,5,3,0]
check_linear_combination(v1,v2,v3, w=w, character='b')

# c
v1,v2,v3 = [1,1,2,2],[2,3,5,6],[2,-1,3,6]
w = [0,5,3,0]
check_linear_combination(v1,v2,v3, w=w, character='c')

# d
v1,v2,v3, v4 = [1,2,3,4],[-1,0,1,3],[0,5,-6,8],[1,15,-12,8]
w = [0,-6,17,11]
check_linear_combination(v1,v2,v3,v4, w=w, character='d')

a: False
b: False
c: False
d: True


In [31]:
# Ex2
# a
v1,v2,v3 = [1,-2,0], [0,-4,1], [1,-1,1]
w = [0,0,0]
check_linear_combination(v1,v2,v3, w=w, character='a')

# d
v1,v2,v3,v4,v5 = [0,0,1,2,3],[0,0,2,3,1],[1,2,3,4,5],[2,1,0,0,0],[-1,-3,-5,0,0]
w = [0,0,0,0,0]
check_linear_combination(v1,v2,v3,v4,v5, w=w, character='d')

a: True
d: True


In [44]:
# Ex3
C = np.array([[1,0,2,3],
              [4,-1,0,2],
              [0,-1,-8,-10]])

row_echelon_form, pivot_col = sp.Matrix(C).rref()

basic_col = C[:, list(pivot_col)]
basic_row = row_echelon_form[list(pivot_col), :]

print("row echelon form\n",np.array(row_echelon_form))
print("basic col\n",np.array(basic_col))
print("basic row\n",np.array(basic_row))

row echelon form
 [[1 0 2 3]
 [0 1 8 10]
 [0 0 0 0]]
basic col
 [[ 1  0]
 [ 4 -1]
 [ 0 -1]]
basic row
 [[1 0 2 3]
 [0 1 8 10]]


In [50]:
# Ex4
A2 = np.array([[1,0,2,3],
               [4,-1,0,2],
               [0,-1,-8,-10]])

A2 = sp.Matrix(A2)
v1, v2 = A2.nullspace()

print("v1:\n", np.array(v1))
print("v2:\n", np.array(v2))

v1:
 [[-2]
 [-8]
 [1]
 [0]]
v2:
 [[-3]
 [-10]
 [0]
 [1]]


In [65]:
# Ex5
def isColSpace(A, w):
  A_extend = np.column_stack((A,w))

  rank_A = np.linalg.matrix_rank(A)
  rank_A_extend = np.linalg.matrix_rank(A_extend)

  return rank_A_extend == rank_A

def isNullSpace(A, w):
  w = w.reshape((A.shape[1], -1))
  res = A @ w
  return np.allclose(res, 0)

def is_col_or_null_space(A, w):
    col_space = isColSpace(A, w)
    null_space = isNullSpace(A, w)

    if col_space and null_space:
        print(f"{w} is both column space and null space of A")
    elif col_space:
        print(f"{w} is column space of A")
    elif null_space:
        print(f"{w} is null space of A")
    else:
        print(f"{w} is neither column space nor null space of A")

# test case a
A = np.array([[7,6,-4,1],
              [-5,-1,0,-2],
              [9,-11,7,-3],
              [19,-9,7,1]])

w = np.array([1,1,-1,-3])

is_col_or_null_space(A, w)
is_col_or_null_space(A, w)

# test case b
A = np.array([[-8,5,-2,0],
              [-5,2,1,-2],
              [10,-8,6,-3],
              [3,-2,1,0]])

w = np.array([1,2,1,0])

is_col_or_null_space(A, w)
is_col_or_null_space(A, w)

[ 1  1 -1 -3] is column space of A
[ 1  1 -1 -3] is column space of A
[1 2 1 0] is both column space and null space of A
[1 2 1 0] is both column space and null space of A


In [72]:
# Ex6
A = np.array([[5,1,2,2,0],
              [3,3,2,-1,-12],
              [8,4,4,-5,12],
              [2,1,1,0,-2]])

a1 = A[:, 0]
a2 = A[:, 1]
a4 = A[:, 3]
a3 = A[:, 2]
a5 = A[:, 4]

A_matrix = np.column_stack((a1, a2, a4))
res1 = isLinearCombanation(A_matrix, a3)
res2 = isLinearCombanation(A_matrix, a5)

print(res1, res2)

True True


In [76]:
# Ex9
import numpy as np

def orthogonal_set(*vectors):
  for i in range(len(vectors) - 1):
    for j in range(i + 1, len(vectors)):
      if np.dot(vectors[i], vectors[j]) != 0:
        print(f"Vectors {vectors[i]} and {vectors[j]} are not orthogonal")
        return False
  return True

u1 = np.array([3, 1, 1])
u2 = np.array([-1, 2, 1])
u3 = np.array([-1/2, 2, 7/2])

res = orthogonal_set(u1, u2, u3)
if res:
    print("The vectors are orthogonal")
else:
    print("The vectors are not orthogonal")


Vectors [3 1 1] and [-0.5  2.   3.5] are not orthogonal
The vectors are not orthogonal


In [79]:
# Ex 11
def is_orthonormal(U):
  UTU = U.T @ U
  return np.allclose(UTU, np.eye(U.shape[1]))

U = np.array([[1,0],
              [0,1]])
is_orthonormal(U)

True

In [81]:
# Ex12
import numpy as np

def gram_schmidt(A):
    n = A.shape[1]
    orthogonal_basis = []
    for i in range(n):
        v_i = A[:, i]
        for j in range(i):
            u_j = orthogonal_basis[j]
            projection = np.dot(v_i, u_j) / np.dot(u_j, u_j) * u_j
            v_i = v_i - projection
        orthogonal_basis.append(v_i)
    return np.array(orthogonal_basis).T

A = np.array([[-10, 13, 7, -11],
              [2, 1, -5, 3],
              [-6, 3, 13, -3],
              [16, -16, -2, 5],
              [2, 1, -5, -7]])

orthogonal_basis = gram_schmidt(A)

print("Orthogonal basis for the column space of A:")
print(orthogonal_basis)

Orthogonal basis for the column space of A:
[[-10.   3.   6.   0.]
 [  2.   3.   0.   5.]
 [ -6.  -3.   6.   0.]
 [ 16.   0.   6.   0.]
 [  2.   3.   0.  -5.]]
