In [1]:
import numpy as np
import math as m

In [2]:
# Ex1
def norm_1(A):
  return max(sum(abs(A[:, j])) for j in range(A.shape[1]))

A1 = np.array([[1,-7],
              [-2,-3]])

A2 = np.array([[-2,8],
               [3,1]])

A3 = np.array([[2,-8],
               [3,1]])

A4 = np.array([[2,3],
               [1,-1]])

A5 = np.array([[5,-4,2],
               [-1,2,3],
               [-2,1,0]])

print("norm 1 by command")
print(norm_1(A1))
print(norm_1(A2))
print(norm_1(A3))
print(norm_1(A4))
print(norm_1(A5))

# verify the result
print("norm 1 by built in function")
print(np.linalg.norm(A1, ord=1))
print(np.linalg.norm(A2, ord=1))
print(np.linalg.norm(A3, ord=1))
print(np.linalg.norm(A4, ord=1))
print(np.linalg.norm(A5, ord=1))

norm 1 by command
10
9
9
4
8
norm 1 by built in function
10.0
9.0
9.0
4.0
8.0


In [3]:
# Ex2
def norm_inf(B):
  return max(sum(abs(B[i, :])) for i in range(B.shape[0]))

B1 = np.array([[1,-7],
               [-2,-3]])

B2 = np.array([[3,6],
               [1,0]])

B3 = np.array([[5,-4,2],
               [-1,2,3],
               [-2,1,0]])

B4 = np.array([[3,6,-1],
               [3,1,0],
               [2,4,-7]])

B5 = np.array([[-3,0,0],
               [0,4,0],
               [0,0,2]])

print("norm inf by command")
print(norm_inf(B1))
print(norm_inf(B2))
print(norm_inf(B3))
print(norm_inf(B4))
print(norm_inf(B5))

norm inf by command
8
9
11
13
4


In [4]:
# Ex 3
def norm_frobenius(C):
  return np.sqrt(np.sum(np.square(C)))

C1 = np.array([[5,-4,2],
               [-1,2,3],
               [-2,1,0]])

C2 = np.array([[1,7,3],
               [4,-2,-2],
               [-2,-1,1]])

C3 = np.array([[2,3],
               [1,-1]])

print("norm Frobenius by command")
print(norm_frobenius(C1))
print(norm_frobenius(C2))
print(norm_frobenius(C3))

norm Frobenius by command
8.0
9.433981132056603
3.872983346207417


In [5]:
# Ex4
def angel(u,v):
  dot_product = np.dot(u,v)

  norm_u = np.linalg.norm(u)
  norm_v = np.linalg.norm(v)

  if norm_u == 0 or norm_v == 0:
    raise ValueError("One of the vectors has zero magnitude, angle is undefined.")

  cos_theta = dot_product/(norm_u * norm_v)
  res = np.arccos(cos_theta)

  return np.degrees(res)

# a
u = np.array([1,1])
v = np.array([0,1])
print(angel(u,v), end="\n--------------\n")

# b
u = np.array([1,0])
v = np.array([0,1])
print(angel(u,v), end="\n--------------\n")

# c
u = np.array([-2,3])
v = np.array([1/2,-1/2])
print(angel(u,v), end="\n--------------\n")


45.00000000000001
--------------
90.0
--------------
168.69006752597974
--------------


In [6]:
# Ex5
def unit_vector(u):
  norm_u = np.linalg.norm(u)
  return u/norm_u

# a
u = np.array([2,3])
print(unit_vector(u), end="\n------------------------\n")

# b
u = np.array([1,2,3])
print(unit_vector(u), end="\n------------------------\n")

# c
u = np.array([1/2,-1/2,1/4])
print(unit_vector(u), end="\n------------------------\n")

# d
u = np.array([m.sqrt(2),2,-m.sqrt(2),m.sqrt(2)])
print(unit_vector(u), end="\n------------------------\n")

[0.5547002  0.83205029]
------------------------
[0.26726124 0.53452248 0.80178373]
------------------------
[ 0.66666667 -0.66666667  0.33333333]
------------------------
[ 0.4472136   0.63245553 -0.4472136   0.4472136 ]
------------------------


In [7]:
# Ex6
def euclidean_distance(v1, v2):
  return np.linalg.norm((v1-v2))

v1 = np.array([1,2,3])
v2 = np.array([7,4,3])
v3 = np.array([2,1,9])

d_v1_v2 = euclidean_distance(v1,v2)
d_v1_v3 = euclidean_distance(v1,v3)
d_v2_v3 = euclidean_distance(v2,v3)

print(f"Distance between v1 and s2: {d_v1_v2}")
print(f"Distance between v1 and s3: {d_v1_v3}")
print(f"Distance between s2 and s3: {d_v2_v3}")

Distance between v1 and s2: 6.324555320336759
Distance between v1 and s3: 6.164414002968976
Distance between s2 and s3: 8.366600265340756


In [8]:
# Ex7
def decode(E, A):
  A_inv = np.linalg.inv(A)
  D = A_inv @ E
  D = np.round(D).astype(int)
  print(D)
  temp = []
  for col in range(D.shape[1]):
    for row in range(D.shape[0]):
      if D[row,col] == 30:
        print("")
      else:
        temp.append(chr(D[row,col] + 61))
  message = ''.join(temp)
  return message

E = np.array([[80,98,99,85,106,94],
              [71,92,76,95,100,92],
              [124,163,140,160,176,161]])

A = np.array([[1,2,3],
              [2,1,2],
              [3,2,4]])

decoded_message = decode(E, A)
print("Decoded Message:", decoded_message)

[[18 21 12 30 24 23]
 [19  4 18  5  8  4]
 [ 8 23 17 15 22 21]]

Decoded Message: OPERATIONBLUESTAR


In [28]:
# Ex8
space_value = 100

def encode_message(message, A):
    message_numbers = [ord(char)-61 if char != " " else space_value for char in message]

    while len(message_numbers) % 3 != 0:
        message_numbers.append(space_value)
    E = np.array(message_numbers).reshape(3, -1)
    encoded = A @ E
    return encoded

A = np.array([
    [3, 4, 5],
    [1, 3, 1],
    [1, 1, 2]
])

message1 = "ATTACK"
message2 = "LINEAR ALGEBRA LABORATORY"

encoded1 = encode_message(message1, A)
encoded2 = encode_message(message2, A)

print("Encoded Message 1:\n", encoded1)
print("Encoded Message 2:\n", encoded2)

Encoded Message 1:
 [[134 155]
 [ 79  49]
 [ 39  55]]
Encoded Message 2:
 [[175 173  91 223 118 568 500 528 565]
 [ 63  57  36  94  34 342 173 116 130]
 [ 61  62  30  75  44 163 171 208 220]]


In [33]:
# Ex9 by chat gpt
doc_matrix = np.array([[0,4,0,0,0,2,1,3],
                      [3,1,4,3,1,2,0,1],
                      [3,0,0,0,3,0,3,0],
                      [0,1,0,3,0,0,2,0],
                      [2,2,2,3,1,4,0,2]])

norms = np.linalg.norm(doc_matrix, axis=1, keepdims=True)
normalized_matrix = doc_matrix/norms
similarity_matrix = np.dot(normalized_matrix, normalized_matrix.T)

print(similarity_matrix)

[[1.         0.31364627 0.10540926 0.29277002 0.61977979]
 [0.31364627 1.         0.36066785 0.41739194 0.86753285]
 [0.10540926 0.36066785 1.         0.3086067  0.26726124]
 [0.29277002 0.41739194 0.3086067  1.         0.45363235]
 [0.61977979 0.86753285 0.26726124 0.45363235 1.        ]]


In [41]:
# Ex9 by student
def cosine_similarity_matrix(doc_matrix, q=None):
  norms = np.linalg.norm(doc_matrix, axis=1)

  if q is None:
    row, col = doc_matrix.shape[0], doc_matrix.shape[0]
    similarity_matrix = np.zeros((row, col))
  else:
    row, col = doc_matrix.shape[0], 1
    similarity_matrix = np.zeros((row, col))

  for i in range(row):
    for j in range(col):
      comparison_vector = q if q is not None else doc_matrix[j]
      comparison_norm = np.linalg.norm(q) if q is not None else norms[j]

      dot_product = np.dot(doc_matrix[i], comparison_vector)
      norm_i_j = norms[i] * comparison_norm
      similarity_matrix[i,j] = dot_product/norm_i_j

  return similarity_matrix

doc_matrix = np.array([[0,4,0,0,0,2,1,3],
                      [3,1,4,3,1,2,0,1],
                      [3,0,0,0,3,0,3,0],
                      [0,1,0,3,0,0,2,0],
                      [2,2,2,3,1,4,0,2]])

res = cosine_similarity_matrix(doc_matrix)
print(res)

[[1.         0.31364627 0.10540926 0.29277002 0.61977979]
 [0.31364627 1.         0.36066785 0.41739194 0.86753285]
 [0.10540926 0.36066785 1.         0.3086067  0.26726124]
 [0.29277002 0.41739194 0.3086067  1.         0.45363235]
 [0.61977979 0.86753285 0.26726124 0.45363235 1.        ]]


In [45]:
# Ex10
doc_matrix = np.array([[1.0, 0.5, 0.3, 0, 0, 0],
                       [0.5, 1.0, 0, 0, 0, 0],
                       [0, 1.0, 0.8, 0.7, 0, 0],
                       [0, 0.9, 1.0, 0.5, 0, 0],
                       [0, 0, 0, 1.0, 0, 1.0],
                       [0, 0, 0, 0, 0.7, 0],
                       [0.5, 0, 0.7, 0, 0, 0.9],
                       [0, 0.6, 0, 1.0, 0.3, 0.2]])

q = np.array([0, 0, 0.7, 0.5, 0, 0.3])

res = cosine_similarity_matrix(doc_matrix, q)

for i, val in enumerate(res):
  print(f"D{i+1}: {val}")

res_flatten = res.flatten()
max_index = np.argmax(res)
max_value = res[max_index]

print(f"\nnearest with vector q: D{max_index+1}: {max_value}")

D1: [0.19912594]
D2: [0.]
D3: [0.68440401]
D4: [0.72652565]
D5: [0.62092042]
D6: [0.]
D7: [0.67005229]
D8: [0.50356536]

nearest with vector q: D4: [0.72652565]
