In [ ]:
import numpy as np
import math
import string

In [ ]:
# exercise 1
x = np.array([1,3,5,2,9])
y = np.array([-1,3,15,27,29])
print(len(x))
print(len(y))

5
5


In [ ]:
# exercise 2

def fibo(n):
  fib = [1,1]
  for i in range(2, n):
    fib.append(fib[-1] + fib[-2])
  return np.array(fib)

def prime(n):
  for i in range(2, math.isqrt(n) + 1):
    if n % i == 0:
      return False
  return n > 1

def triangular_numbers(n):
  return np.array([i*(i+1)/2 for i in range(1, n+1)])

list_prime = [i for i in range(24) if prime(i)]

fib_number = fibo(10)

b = np.arange(12, 33, 2)
c = np.arange(31, 52, 2)
x = np.arange(-5,6)
y = np.arange(5, -6, -1)
z = np.arange(10, -5, -2)
w = np.array([1/(2**n) for n in range(10)])
d = np.array([1/fib_number[i] for i in range(len(fib_number))])
e = np.array([1/list_prime[i] for i in range(len(list_prime))])
a = triangular_numbers(8)

denominators = [2]

# Generate the denominators using the identified pattern
for n in range(2, 4 + 1):
    next_denominator = denominators[-1] + (2 * n - 1)
    denominators.append(next_denominator)

n = np.array([1 / d for d in denominators])
#-----------------------------------------------
numerators = [i for i in range(5)]
denominators = [i for i in range(1,6)]

p = np.array([numerators[i]/denominators[i] for i in range(len(denominators))])
#--------------------------------------------------
o = np.array(list(string.ascii_lowercase))

#--------------------------------------------------
characters = [chr(i) for i in range(ord('A'), ord('Z') + 1)]
s = np.array(list(characters[::3]))
print(s)

['A' 'D' 'G' 'J' 'M' 'P' 'S' 'V' 'Y']


In [ ]:
'''Exercise 3'''
x = np.logspace(1, 10, 10, base=10, dtype=int)
print(x)

[         10         100        1000       10000      100000     1000000
    10000000   100000000  1000000000 10000000000]


In [ ]:
'''Exercise 4'''
# x = [1,2,3]
# y = [98,12,33]
# z = x + y
# print(z)

x = np.array([1,2,3])
y = np.array([98,12,33])

z = np.concatenate((x,y))
print(z)

[ 1  2  3 98 12 33]


In [ ]:
'''Exercise 5'''
x = [1,2,3]
y = [4,5,6]
z = np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [ ]:
'''Exercise 6'''
x = np.arange(0,21,2)
print(x)
# solution for a
a = x[:6]
# solution for b
b = x[-5:]
# solution for c
c = [x[i] for i in (0,3,-1)]
# solution for d
d = [x[i] for i in range(0,8,2)]
# solution for e
e = x[1::2]
# solution for f
f = x[::2]

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
'''Exercise 7'''
x = np.array([3,11,-9,-131,-1,1,-11,91,-6,407,-12,-11,12,153,371])
import math

# solution a
a = np.max(x)
# solution b
b = np.min(x)
# solution c
c = [i for i in range(len(x)) if x[i] > 10]
# solution d
d = x[::-1]
d2 = np.flip(x)
# solution e
e = np.sort(x)
# solution f
f = e[::-1]
# solution g
g = sum(x[i] + x[j] == 0 for i in range(len(x)-1) for j in range(i+1,len(x)))
# solution h
h = sum(x[i] == x[j] for i in range(len(x)-1) for j in range(i+1,len(x)))
# solution i
y = [x[i] + x[len(x)-i-1] for i in range(len(x))]
# solution j
def is_Arm_Number(n):
  if n > 0:
    b = int(math.log(n,10)) + 1
    res = 0
    original_n = n
    while n >= 10:
      res += (n%10)**b
      n //= 10
    res += (n%10)**b
    return res == original_n

w = [x[i] for i in range(len(x)) if is_Arm_Number(x[i])]

# solution k
new_x = [a for a in x if a > 0]

# solution l
median_value = np.median(x)

# solution m
mean_value = np.mean(x)
solution = sum(a for a in x if a < mean_value)

# solution n
absolute_x = np.abs(x)
print(absolute_x)

[  3  11   9 131   1   1  11  91   6 407  12  11  12 153 371]
