In [ ]:
# library
import numpy as np

In [ ]:
# Exercise 1
x = np.arange(1,6)
b = np.arange(1,7)
c = np.arange(1,31)
d= np.arange(1,26)


A = np.tile(np.arange(1,6).reshape((-1,1)), 5)
B = np.tile(np.arange(1,7),(6,1))
C = np.arange(1,31).reshape((5,6)).T
D = np.arange(1,26).reshape((5,5))

print(x,b,c,d,A,B,C,D, sep= '\n' + '-'*50 + '\n')

[1 2 3 4 5]
--------------------------------------------------
[1 2 3 4 5 6]
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
--------------------------------------------------
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
--------------------------------------------------
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
--------------------------------------------------
[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]
--------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# Exercise 2
matrix = np.random.randint(1,10, (5,6))
matrix

array([[5, 4, 1, 3, 1, 6],
       [1, 4, 3, 4, 9, 3],
       [2, 1, 1, 9, 1, 7],
       [4, 4, 9, 7, 8, 9],
       [7, 8, 7, 9, 1, 5]])

In [ ]:
# Exercise 3
matrix_A = np.arange(1,10).reshape((3,3))
matrix_B = np.flip(matrix_A, axis=1)
matrix_B

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
# Exercise 4
matrix_B = np.flip(matrix_A, axis=0)
matrix_B

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
# Exercise 5
Y = np.array([[1,2,16,31,22],
              [2,8,12,21,23],
              [4,9,11,14,25],
              [3,6,10,16,34]])

x = Y[1, 1:4]
y = Y[:, 2]
A = Y[1:3, 1:4]
B = Y[:, ::2,]
C = Y[1:4, [0,2,3,4]]
D = Y[Y > 12]

print(x,y,A,B,C,D, sep= '\n' + '-'*50 + '\n')

[ 8 12 21]
--------------------------------------------------
[16 12 11 10]
--------------------------------------------------
[[ 8 12 21]
 [ 9 11 14]]
--------------------------------------------------
[[ 1 16 22]
 [ 2 12 23]
 [ 4 11 25]
 [ 3 10 34]]
--------------------------------------------------
[[ 2 12 21 23]
 [ 4 11 14 25]
 [ 3 10 16 34]]
--------------------------------------------------
[16 31 22 21 23 14 25 16 34]


In [ ]:
# Exercise 6
A = np.array([[2,4,1],
              [6,7,2],
              [3,5,9]])

x1 = A[0,:]
Y = A[1:, :]

print(x1,Y, sep= '\n' + '-'*50 + '\n')

[2 4 1]
--------------------------------------------------
[[6 7 2]
 [3 5 9]]


In [ ]:
# Exercise 7
A = np.array([[2,7,9,7],
              [3,1,5,6],
              [8,1,2,5]])

B = A[:, 1::2]
C = A[0::2, :]
A_T = A.T

print(B, C, A_T, sep= '\n' + '-'*50 + '\n')

[[7 7]
 [1 6]
 [1 5]]
--------------------------------------------------
[[2 7 9 7]
 [8 1 2 5]]
--------------------------------------------------
[[2 3 8]
 [7 1 1]
 [9 5 2]
 [7 6 5]]


In [ ]:
# Exercise 8

A = np.array([[12,15,10,16,12],
              [5,9,14,7,10],
              [8,12,10,9,12]])

Cost = np.array([2,1,3])

total_cost = Cost @ A
total_cost

array([53, 75, 64, 66, 70])

In [ ]:
# Exercise 9

In [ ]:
# Exercise 10
A = np.array([[-1,4,8],
              [-9,1,2]])

B = np.array([[5,8],
              [0,-6],
              [5,6]])

C = np.array([[-4,1],
              [6,5]])

D = np.array([[-6,3,1],
              [8,9,-2],
              [6,-1,5]])

def Multiply(m1, m2):
  row1, col1 = m1.shape
  row2, col2 = m2.shape
  if col1 == row2:
    return m1 @ m2
  else:
    return 'Dimensional error: Can not multiply'

def Add(m1, m2):
  if m1.shape == m2.shape:
    return m1 + m2
  else:
    return 'Dimensional error: Can not Add'

def Sub(m1, m2):
  if m1.shape == m2.shape:
    return m1 - m2
  else:
    return 'Dimensional error: Can not Sub'

a = Multiply(A, B.T)
b = Multiply(B, C.T)
c = Sub(C, C.T)
d = Sub(D, D.T)
e = D.T.T
f = 2*C.T
g = A.T + B
h = Add(A.T, B).T
i = Sub(2*A.T, 5*B).T
j = (-D).T
k = (-D).T
l = (C**2).T
m = (C.T)**2

print(a,b,c,d,e,f,g,h,i,j,k,l,m, sep= '\n' + '-'*50 + '\n')

Dimensional error: Can not multiply
--------------------------------------------------
[[-12  70]
 [ -6 -30]
 [-14  60]]
--------------------------------------------------
[[ 0 -5]
 [ 5  0]]
--------------------------------------------------
[[ 0 -5 -5]
 [ 5  0 -1]
 [ 5  1  0]]
--------------------------------------------------
[[-6  3  1]
 [ 8  9 -2]
 [ 6 -1  5]]
--------------------------------------------------
[[-8 12]
 [ 2 10]]
--------------------------------------------------
[[ 4 -1]
 [ 4 -5]
 [13  8]]
--------------------------------------------------
[[ 4  4 13]
 [-1 -5  8]]
--------------------------------------------------
[[-27   8  -9]
 [-58  32 -26]]
--------------------------------------------------
[[ 6 -8 -6]
 [-3 -9  1]
 [-1  2 -5]]
--------------------------------------------------
[[ 6 -8 -6]
 [-3 -9  1]
 [-1  2 -5]]
--------------------------------------------------
[[16 36]
 [ 1 25]]
--------------------------------------------------
[[16 36]
 [ 1 25]]


In [ ]:
# Exercise 11
A = np.array([[2,4,1],
              [6,7,2],
              [3,5,9]])

def isSquare(A):
  return True if A.shape[0] == A.shape[1] else False

def isSymmetric(A):
  return True if np.array_equal(A, A.T) else False

def isSkewSymmetric(A):
  return True if np.array_equal(-A, A.T) else False

a = isSquare(A)
b = isSymmetric(A)
c = isSkewSymmetric(A)
d = np.triu(A)
e = np.tril(A)

print(a,b,c,d,e, sep= '\n' + '-'*50 + '\n')

True
--------------------------------------------------
False
--------------------------------------------------
False
--------------------------------------------------
[[2 4 1]
 [0 7 2]
 [0 0 9]]
--------------------------------------------------
[[2 0 0]
 [6 7 0]
 [3 5 9]]


In [ ]:
# Exercise 12
A = np.array([[6,0,0,5],
              [1,7,2,-5],
              [2,0,0,0],
              [8,3,1,8]])

B = np.array([[1,-2,5,2],
              [0,0,3,0],
              [2,-6,-7,5],
              [5,0,4,4]])

C = np.array([[3,5,-8,4],
              [0,-2,3,-7],
              [0,0,1,5],
              [0,0,0,2]])

D = np.array([[4,0,0,0],
              [7,-1,0,0],
              [2,6,3,0],
              [5,-8,3,0],
              [5,-8,4,-3]])

E = np.array([[4,0,-7,3,-5],
              [0,0,2,0,0],
              [7,3,-6,4,-8],
              [5,0,5,2,-3],
              [0,0,9,-1,2]])

F = np.array([[6,3,2,4,0],
              [9,0,-4,1,0],
              [8,-5,6,7,1],
              [3,0,0,0,0],
              [4,2,3,2,0]])


def isSquare(matrix):
  row,col = matrix.shape
  return True if row == col else False

def det(matrix):
  return np.linalg.det(matrix) if isSquare(matrix) else 'matrix must be square'


det_A = det(A)
det_B = det(B)
det_C = det(C)
det_D = det(D)
det_E = det(E)
det_F = det(F)

print(det_A, det_B, det_C, det_D, det_E, det_F, sep= '\n' + '-'*50 + '\n')

10.000000000000007
--------------------------------------------------
-5.999999999999997
--------------------------------------------------
-12.0
--------------------------------------------------
matrix must be square
--------------------------------------------------
5.999999999999996
--------------------------------------------------
9.000000000000014


In [ ]:
# Exercise 13

def determinant_difference(n):
    A = np.random.randint(0,10, size=(n, n))
    B = np.random.randint(0,10, size=(n, n))

    det_A = np.linalg.det(A)
    det_B = np.linalg.det(B)
    det_A_plus_B = np.linalg.det(A + B)

    difference = det_A_plus_B - det_A - det_B
    return difference

sizes = [2, 3, 4, 5]

determinant_differences = {n: determinant_difference(n) for n in sizes}
determinant_differences

{2: -41.000000000000036, 3: -60.0, 4: 533.9999999999997, 5: 12555.999999999978}

In [ ]:
# Exercise 14

def determinant_product_check(n):
    A = np.random.randint(0,10, size=(n, n))
    B = np.random.randint(0,10, size=(n, n))

    det_A = np.linalg.det(A)
    det_B = np.linalg.det(B)
    det_AB = np.linalg.det(np.dot(A, B))

    product_det_A_B = det_A * det_B
    return det_AB, product_det_A_B

sizes = [2, 3, 4, 5]

determinant_product_results = [determinant_product_check(n) for n in sizes]
determinant_product_results


[(-343.00000000000017, -342.9999999999999),
 (11703.999999999984, 11704.000000000004),
 (-4330239.999999995, -4330240.0),
 (-25396349.999999955, -25396350.000000004)]

In [ ]:
# Exercise 15


A = np.array([[2, 4, 5/2],
              [-3/4, 1/4, 1/2],
              [1/4, 1/2, 2]])

B = np.array([[1, -1/2, 3/4],
              [1/3, 1/2, -2],
              [1/4, 1, 1/2]])

# a
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

A_inv_B_inv = np.dot(A_inv, B_inv)

AB_inv = np.linalg.inv(np.dot(A, B))
BA_inv = np.linalg.inv(np.dot(B, A))

A_inv_B_inv, AB_inv, BA_inv



# b
A_inv_T = A_inv.T
A_T_inv = np.linalg.inv(A.T)

print(A_inv_B_inv, AB_inv, BA_inv, A_inv_T, A_T_inv, sep= '\n' + '-'*50 + '\n')

[[ 0.33057718 -0.21051361 -0.87231175]
 [ 0.04989237  0.36550184  0.41362384]
 [-0.01577243 -0.27038445  0.12730601]]
--------------------------------------------------
[[ 0.1182932  -0.73003802  0.14871145]
 [-0.03975295  0.34329169  0.37451466]
 [-0.12778884 -0.32156437  0.36180015]]
--------------------------------------------------
[[ 0.33057718 -0.21051361 -0.87231175]
 [ 0.04989237  0.36550184  0.41362384]
 [-0.01577243 -0.27038445  0.12730601]]
--------------------------------------------------
[[ 0.04232804  0.27513228 -0.07407407]
 [-1.14285714  0.57142857  0.        ]
 [ 0.23280423 -0.48677249  0.59259259]]
--------------------------------------------------
[[ 0.04232804  0.27513228 -0.07407407]
 [-1.14285714  0.57142857 -0.        ]
 [ 0.23280423 -0.48677249  0.59259259]]
