In [ ]:
import numpy as np

In [ ]:
np.random.seed(42)

In [ ]:
# Ex16
A = np.random.randint(1,10, size=(100,100))
out_matrix = np.where(A > 5, 1, np.where(A < 5, 0, A))

out_matrix

array([[1, 0, 1, ..., 1, 0, 0],
       [0, 5, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 0, 0],
       ...,
       [0, 5, 0, ..., 0, 1, 1],
       [5, 0, 1, ..., 1, 1, 0],
       [5, 0, 1, ..., 1, 1, 1]])

In [ ]:
# Ex17
A = np.random.randint(1,10, size=(100,100))
diagonal_sum = np.trace(A)

diagonal_sum

483

In [ ]:
# Ex18

def magic_square(n):
    if n % 2 == 0:
        raise ValueError("Magic square is only possible for odd dimensions.")

    magic_square = np.zeros((n, n), dtype=int)

    num = 1
    i, j = 0, n // 2

    while num <= n**2:
        magic_square[i, j] = num
        num += 1
        new_i, new_j = (i - 1) % n, (j + 1) % n

        if magic_square[new_i, new_j]:
            i += 1
        else:
            i, j = new_i, new_j

    return magic_square

n = 15
magic_square_matrix = magic_square(n)

magic_square_matrix

array([[122, 139, 156, 173, 190, 207, 224,   1,  18,  35,  52,  69,  86,
        103, 120],
       [138, 155, 172, 189, 206, 223,  15,  17,  34,  51,  68,  85, 102,
        119, 121],
       [154, 171, 188, 205, 222,  14,  16,  33,  50,  67,  84, 101, 118,
        135, 137],
       [170, 187, 204, 221,  13,  30,  32,  49,  66,  83, 100, 117, 134,
        136, 153],
       [186, 203, 220,  12,  29,  31,  48,  65,  82,  99, 116, 133, 150,
        152, 169],
       [202, 219,  11,  28,  45,  47,  64,  81,  98, 115, 132, 149, 151,
        168, 185],
       [218,  10,  27,  44,  46,  63,  80,  97, 114, 131, 148, 165, 167,
        184, 201],
       [  9,  26,  43,  60,  62,  79,  96, 113, 130, 147, 164, 166, 183,
        200, 217],
       [ 25,  42,  59,  61,  78,  95, 112, 129, 146, 163, 180, 182, 199,
        216,   8],
       [ 41,  58,  75,  77,  94, 111, 128, 145, 162, 179, 181, 198, 215,
          7,  24],
       [ 57,  74,  76,  93, 110, 127, 144, 161, 178, 195, 197, 214,   6,
       

In [ ]:
# Ex19
matrix = np.zeros((100, 100), dtype=int)

matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

matrix

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
# Ex20

np.random.seed(42)
matrix = np.random.randint(1, 10, size=(100, 100))

bordered_matrix = np.zeros((102, 102), dtype=int)

bordered_matrix[1:-1, 1:-1] = matrix

bordered_matrix


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 7, 4, ..., 3, 1, 0],
       [0, 3, 5, ..., 2, 8, 0],
       ...,
       [0, 5, 3, ..., 8, 1, 0],
       [0, 5, 3, ..., 9, 7, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# Ex21
matrix = np.random.randint(1, 10, size=(100, 100))

sorted_matrix = np.sort(matrix, axis=1)

sorted_matrix

array([[1, 1, 1, ..., 9, 9, 9],
       [1, 1, 1, ..., 9, 9, 9],
       [1, 1, 1, ..., 9, 9, 9],
       ...,
       [1, 1, 1, ..., 9, 9, 9],
       [1, 1, 1, ..., 9, 9, 9],
       [1, 1, 1, ..., 9, 9, 9]])

In [60]:
# Ex22
matrix = np.random.randint(1, 101, size=(100, 100))

multiples_of_3_or_5 = (matrix % 3 == 0) | (matrix % 5 == 0)

total_sum = np.sum(matrix[multiples_of_3_or_5])

print("Sum of all multiples of 3 or 5:", total_sum)


Sum of all multiples of 3 or 5: 245071


In [ ]:
# Ex23

np.random.seed(42)
matrix = np.random.randint(1, 1001, size=(3, 3))

five_smallest_elements = np.sort(matrix, axis=None)[:5]

print("Five smallest elements:", five_smallest_elements)


Five smallest elements: [ 21  72 103 107 271]
