In [28]:
import numpy as np

In [29]:
np.random.seed(42)
A = np.random.randint(1, 99, size=(10,10))
A

array([[52, 93, 15, 72, 61, 21, 83, 87, 75, 75],
       [88, 24,  3, 22, 53,  2, 88, 30, 38,  2],
       [64, 60, 21, 33, 76, 58, 22, 89, 49, 91],
       [59, 42, 92, 60, 80, 15, 62, 62, 47, 62],
       [51, 55, 64,  3, 51,  7, 21, 73, 39, 18],
       [ 4, 89, 60, 14,  9, 90, 53,  2, 84, 92],
       [60, 71, 44,  8, 47, 35, 78, 81, 36, 50],
       [ 4,  2,  6, 54,  4, 54, 93, 63, 18, 90],
       [44, 34, 74, 62, 14, 95, 48, 15, 72, 78],
       [87, 62, 40, 85, 80, 82, 53, 24, 26, 89]])

In [30]:
# Ex12
odd_columns = A[:,::2]
odd_columns

array([[52, 15, 61, 83, 75],
       [88,  3, 53, 88, 38],
       [64, 21, 76, 22, 49],
       [59, 92, 80, 62, 47],
       [51, 64, 51, 21, 39],
       [ 4, 60,  9, 53, 84],
       [60, 44, 47, 78, 36],
       [ 4,  6,  4, 93, 18],
       [44, 74, 14, 48, 72],
       [87, 40, 80, 53, 26]])

In [31]:
# Ex13
even_rows = A[1::2,:]
even_rows

array([[88, 24,  3, 22, 53,  2, 88, 30, 38,  2],
       [59, 42, 92, 60, 80, 15, 62, 62, 47, 62],
       [ 4, 89, 60, 14,  9, 90, 53,  2, 84, 92],
       [ 4,  2,  6, 54,  4, 54, 93, 63, 18, 90],
       [87, 62, 40, 85, 80, 82, 53, 24, 26, 89]])

In [32]:
# Ex14
even_integer = A[A % 2 == 0]
even_integer

array([52, 72, 88, 24, 22,  2, 88, 30, 38,  2, 64, 60, 76, 58, 22, 42, 92,
       60, 80, 62, 62, 62, 64, 18,  4, 60, 14, 90,  2, 84, 92, 60, 44,  8,
       78, 36, 50,  4,  2,  6, 54,  4, 54, 18, 90, 44, 34, 74, 62, 14, 48,
       72, 78, 62, 40, 80, 82, 24, 26])

In [33]:
# Ex15
res = A[::2, ::-1]
res

array([[75, 75, 87, 83, 21, 61, 72, 15, 93, 52],
       [91, 49, 89, 22, 58, 76, 33, 21, 60, 64],
       [18, 39, 73, 21,  7, 51,  3, 64, 55, 51],
       [50, 36, 81, 78, 35, 47,  8, 44, 71, 60],
       [78, 72, 15, 48, 95, 14, 62, 74, 34, 44]])

In [36]:
# Ex16
max = np.max(A)
B = np.copy(A)

B = np.where(B % 2 != 0, max, B)

B

array([[52, 95, 95, 72, 95, 95, 95, 95, 95, 95],
       [88, 24, 95, 22, 95,  2, 88, 30, 38,  2],
       [64, 60, 95, 95, 76, 58, 22, 95, 95, 95],
       [95, 42, 92, 60, 80, 95, 62, 62, 95, 62],
       [95, 95, 64, 95, 95, 95, 95, 95, 95, 18],
       [ 4, 95, 60, 14, 95, 90, 95,  2, 84, 92],
       [60, 95, 44,  8, 95, 95, 78, 95, 36, 50],
       [ 4,  2,  6, 54,  4, 54, 95, 95, 18, 90],
       [44, 34, 74, 62, 14, 95, 48, 95, 72, 78],
       [95, 62, 40, 95, 80, 82, 95, 24, 26, 95]])

In [37]:
# Ex17
B = np.copy(A)

B[:, [0, -1]] = B[:, [-1,0]]

B

array([[75, 93, 15, 72, 61, 21, 83, 87, 75, 52],
       [ 2, 24,  3, 22, 53,  2, 88, 30, 38, 88],
       [91, 60, 21, 33, 76, 58, 22, 89, 49, 64],
       [62, 42, 92, 60, 80, 15, 62, 62, 47, 59],
       [18, 55, 64,  3, 51,  7, 21, 73, 39, 51],
       [92, 89, 60, 14,  9, 90, 53,  2, 84,  4],
       [50, 71, 44,  8, 47, 35, 78, 81, 36, 60],
       [90,  2,  6, 54,  4, 54, 93, 63, 18,  4],
       [78, 34, 74, 62, 14, 95, 48, 15, 72, 44],
       [89, 62, 40, 85, 80, 82, 53, 24, 26, 87]])

In [39]:
# Ex18
first_row = A[0,:]
last_row = A[-1,:]
first_column = A[:, 0]
last_column = A[:, -1]

sum = np.sum(np.concatenate((first_row, last_row, first_column, last_column)))

sum

2422

In [41]:
# Ex19
n = A.shape[0]

# Calculate sum of major and minor diagonals
major_diag_sum = np.sum(np.diag(A))  # Sum of major diagonal
minor_diag_sum = np.sum(np.diag(np.fliplr(A)))  # Sum of minor diagonal

# Handle the case where the center element is counted twice (only for odd n)
if n % 2 != 0:
    center_value = A[n // 2, n // 2]
    total_sum = major_diag_sum + minor_diag_sum - center_value
else:
    total_sum = major_diag_sum + minor_diag_sum

print("Sum of major and minor diagonal elements:", total_sum)

Sum of major and minor diagonal elements: 1015


In [42]:
# Ex20
A = np.array([[1,1,1,1],
             [1,2,4,8],
             [1,3,9,27],
             [1,4,16,64]])

b = np.array([1000,2000,3000,400])

solution = np.linalg.solve(A, b)

solution

array([ 3600., -5600.,  3600.,  -600.])